"""Archivist agent for final-stage living artifacts and traceable reuse."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import logging

from src.config import AppSettings
from src.index.semantic_index import build_semantic_index
from src.llm.openrouter import OpenRouterProvider
from src.llm.provider import LLMProvider, NullProvider
from src.models.archivist import (
    CodebaseContextDocument,
    CodebaseSectionEntry,
    IncrementalBaseline,
    OnboardingBrief,
    OnboardingQuestionSection,
    SemanticIndexSnapshot,
)
from src.models.artifacts import SerializationMetadata
from src.models.enums import ConfidenceBand
from src.models.graph import DatasetNode, GraphPayload, GraphNode, ModuleNode, SurveySummaryPayload
from src.models.semantic import (
    DayOneAnswersPayload,
    DocumentationDriftPayload,
    DomainMapPayload,
    EvidenceReference,
    ModuleSemanticsPayload,
)
from src.models.trace import TraceEvent
from src.utils.citations import dedupe_references, derive_confidence, evidence_record_to_reference, format_evidence_reference
from src.utils.incremental import git_head_commit
from src.utils.logging import log_event
from src.utils.trace import TraceWriter


@dataclass(slots=True)
class ArchivistResult:
    """Final-stage output bundle generated by Archivist."""

    codebase_document: CodebaseContextDocument
    codebase_markdown: str
    onboarding_brief: OnboardingBrief
    onboarding_markdown: str
    semantic_index_snapshot: SemanticIndexSnapshot
    incremental_baseline: IncrementalBaseline
    trace_event_ids: list[str]
    warning_codes: list[str]
    partial_result_flags: list[str]


class ArchivistAgent:
    """Generate final living artifacts from Surveyor, Hydrologist, and Semanticist outputs."""

    def __init__(self, settings: AppSettings, provider: LLMProvider | None = None):
        self.settings = settings
        self.provider = provider or self._build_provider()

    def analyze(
        self,
        *,
        repo_root: Path,
        run_id: str,
        artifact_dir: str,
        run_dir: Path,
        module_graph: GraphPayload,
        survey_summary: SurveySummaryPayload,
        lineage_graph: GraphPayload,
        module_semantics: ModuleSemanticsPayload,
        documentation_drift: DocumentationDriftPayload,
        domain_map: DomainMapPayload,
        day_one_answers: DayOneAnswersPayload,
        reused_artifact_paths: list[str] | None = None,
        regenerated_artifact_paths: list[str] | None = None,
        logger: logging.Logger | None = None,
    ) -> ArchivistResult:
        metadata = SerializationMetadata(run_id=run_id, artifact_dir=artifact_dir.replace("\\", "/"))
        trace_writer = TraceWriter(self.settings.trace_log_path(run_dir))
        trace_event_ids: list[str] = []
        warnings: list[str] = []
        partial_flags: list[str] = []

        if logger:
            log_event(logger, event="archivist_started", run_id=run_id)

        codebase_document = self.generate_codebase_document(
            metadata=metadata,
            repo_root=repo_root,
            module_graph=module_graph,
            survey_summary=survey_summary,
            lineage_graph=lineage_graph,
            module_semantics=module_semantics,
            documentation_drift=documentation_drift,
            domain_map=domain_map,
        )
        codebase_markdown = self.generate_CODEBASE_md(codebase_document)
        event = trace_writer.append(
            TraceEvent(
                run_id=run_id,
                agent="archivist",
                action="generate_codebase_md",
                input_summary={
                    "module_count": len(module_graph.nodes),
                    "dataset_count": len([node for node in lineage_graph.nodes if isinstance(node, DatasetNode)]),
                },
                output_summary={"critical_path_entries": len(codebase_document.critical_path_entries)},
                evidence_sources=codebase_document.evidence_references[:8],
                confidence=derive_confidence(codebase_document.evidence_references),
                method_type="synthesis",
            )
        )
        trace_event_ids.append(event.event_id or "")

        onboarding_brief = self.generate_onboarding_brief(
            metadata=metadata,
            analysis_root=str(repo_root),
            day_one_answers=day_one_answers,
        )
        onboarding_markdown = self.render_onboarding_brief(onboarding_brief)
        event = trace_writer.append(
            TraceEvent(
                run_id=run_id,
                agent="archivist",
                action="generate_onboarding_brief",
                input_summary={"question_count": len(day_one_answers.answers)},
                output_summary={"section_count": len(onboarding_brief.sections)},
                evidence_sources=dedupe_references(
                    [reference for answer in day_one_answers.answers for reference in answer.evidence_references],
                    limit=8,
                ),
                confidence=ConfidenceBand.MEDIUM,
                method_type="synthesis",
            )
        )
        trace_event_ids.append(event.event_id or "")

        commit_hash = git_head_commit(repo_root)
        semantic_index_snapshot = build_semantic_index(
            module_semantics.profiles,
            run_id=run_id,
            index_dir=self.settings.semantic_index_dir(run_dir),
            commit_hash=commit_hash,
            provider=self.provider if self.provider.is_available() else None,
            embedding_model=self.settings.semantic_embedding_model,
        )
        warnings.extend(semantic_index_snapshot.warning_codes)
        if semantic_index_snapshot.used_fallback_indexing:
            partial_flags.append("semantic_index_fallback")
        event = trace_writer.append(
            TraceEvent(
                run_id=run_id,
                agent="archivist",
                action="build_semantic_index",
                input_summary={"profile_count": len(module_semantics.profiles)},
                output_summary={
                    "entry_count": semantic_index_snapshot.entry_count,
                    "used_fallback_indexing": semantic_index_snapshot.used_fallback_indexing,
                },
                evidence_sources=dedupe_references(
                    [reference for profile in module_semantics.profiles for reference in profile.evidence_references],
                    limit=8,
                ),
                confidence=ConfidenceBand.MEDIUM if not semantic_index_snapshot.used_fallback_indexing else ConfidenceBand.LOW,
                method_type="llm" if not semantic_index_snapshot.used_fallback_indexing else "reuse",
            )
        )
        trace_event_ids.append(event.event_id or "")

        baseline = IncrementalBaseline(
            run_id=run_id,
            commit_hash=commit_hash,
            source_files=sorted(
                {
                    *(node.relative_path for node in module_graph.nodes if isinstance(node, ModuleNode)),
                    *(profile.relative_path for profile in module_semantics.profiles),
                    *(record.module_path for record in documentation_drift.drift_records),
                }
            ),
            upstream_artifact_paths=[
                "module_graph.json",
                "survey_summary.json",
                "lineage_graph.json",
                "module_semantics.json",
                "documentation_drift.json",
                "domain_map.json",
                "day_one_answers.json",
            ],
            dependency_keys=[
                *(profile.module_id for profile in module_semantics.profiles),
                *(domain.domain_id or "" for domain in domain_map.domains),
            ],
            reusable_artifacts=[*(reused_artifact_paths or []), "lineage_graph.json"],
        )

        event = trace_writer.append(
            TraceEvent(
                run_id=run_id,
                agent="archivist",
                action="finalize_archivist_bundle",
                input_summary={
                    "reused_artifact_count": len(reused_artifact_paths or []),
                    "regenerated_artifact_count": len(regenerated_artifact_paths or []),
                },
                output_summary={"warning_count": len(warnings), "partial_flag_count": len(partial_flags)},
                evidence_sources=codebase_document.evidence_references[:6],
                confidence=ConfidenceBand.MEDIUM,
                method_type="reuse" if reused_artifact_paths else "synthesis",
                reuse_status="reused" if reused_artifact_paths else "regenerated",
            )
        )
        trace_event_ids.append(event.event_id or "")

        if logger:
            log_event(
                logger,
                event="archivist_completed",
                run_id=run_id,
                codebase_sections=6,
                onboarding_section_count=len(onboarding_brief.sections),
                semantic_index_entries=semantic_index_snapshot.entry_count,
                trace_event_count=len(trace_event_ids),
            )

        return ArchivistResult(
            codebase_document=codebase_document,
            codebase_markdown=codebase_markdown,
            onboarding_brief=onboarding_brief,
            onboarding_markdown=onboarding_markdown,
            semantic_index_snapshot=semantic_index_snapshot,
            incremental_baseline=baseline,
            trace_event_ids=trace_event_ids,
            warning_codes=sorted(dict.fromkeys(warnings)),
            partial_result_flags=sorted(dict.fromkeys(partial_flags)),
        )

    def generate_codebase_document(
        self,
        *,
        metadata: SerializationMetadata,
        repo_root: Path,
        module_graph: GraphPayload,
        survey_summary: SurveySummaryPayload,
        lineage_graph: GraphPayload,
        module_semantics: ModuleSemanticsPayload,
        documentation_drift: DocumentationDriftPayload,
        domain_map: DomainMapPayload,
    ) -> CodebaseContextDocument:
        """Assemble the structured CODEBASE content from upstream artifacts."""

        module_nodes = sorted((node for node in module_graph.nodes if isinstance(node, ModuleNode)), key=lambda item: item.relative_path)
        dataset_nodes = sorted((node for node in lineage_graph.nodes if isinstance(node, DatasetNode)), key=lambda item: item.canonical_name)
        profile_by_module = {profile.module_id: profile for profile in module_semantics.profiles}

        architecture_refs = dedupe_references(
            [
                *(
                    evidence_record_to_reference(record, source_kind="module_graph", artifact_path="module_graph.json")
                    for module in module_nodes[:3]
                    for record in module.evidence[:1]
                ),
                *(
                    reference
                    for domain in domain_map.domains[:2]
                    for module_id in domain.module_ids[:2]
                    for profile in [profile_by_module.get(module_id)]
                    if profile is not None
                    for reference in profile.evidence_references[:1]
                ),
            ],
            limit=8,
        )
        domain_labels = ", ".join(domain.label for domain in domain_map.domains[:3]) or "shared utilities"
        architecture_overview = (
            f"The repository contains {len(module_nodes)} analyzed modules, {len(dataset_nodes)} datasets, and "
            f"{len(domain_map.domains)} inferred domains. Business logic is concentrated around {domain_labels}, "
            f"with lineage and semantic signals stitched together from the Surveyor, Hydrologist, and Semanticist stages."
        )

        critical_path_entries = [
            self._module_entry(module, profile_by_module.get(module.node_id), f"PageRank {module.pagerank_score or 0:.3f}")
            for module in sorted(
                module_nodes,
                key=lambda item: (-(item.pagerank_score or 0.0), item.relative_path, item.node_id or ""),
            )[:5]
        ]

        source_entries = [self._dataset_entry(node, "Entry-point dataset or file source") for node in self._find_lineage_boundary_nodes(lineage_graph, "sources")[:5]]
        sink_entries = [self._dataset_entry(node, "Downstream sink dataset") for node in self._find_lineage_boundary_nodes(lineage_graph, "sinks")[:5]]

        known_debt_entries: list[CodebaseSectionEntry] = []
        for cycle in survey_summary.circular_dependencies[:5]:
            refs: list[EvidenceReference] = []
            for path in cycle.relative_paths[:2]:
                module = next((item for item in module_nodes if item.relative_path == path), None)
                if module is not None and module.evidence:
                    refs.append(evidence_record_to_reference(module.evidence[0], source_kind="module_graph", artifact_path="module_graph.json"))
            known_debt_entries.append(
                CodebaseSectionEntry(
                    title="Circular dependency",
                    summary=" -> ".join(cycle.relative_paths),
                    citations=dedupe_references(refs, limit=4),
                    confidence=ConfidenceBand.MEDIUM,
                    is_inferred=True,
                )
            )
        for drift in documentation_drift.drift_records[:5]:
            known_debt_entries.append(
                CodebaseSectionEntry(
                    title=f"Documentation drift: {drift.drift_type}",
                    summary=f"{drift.module_path} no longer matches its nearby documentation.",
                    citations=dedupe_references(drift.evidence_references, limit=4),
                    confidence=drift.confidence,
                    is_inferred=True,
                )
            )

        change_velocity_entries = [
            CodebaseSectionEntry(
                title=record.relative_path,
                summary=f"Observed {record.change_count} changes in the last {record.lookback_days} days.",
                citations=dedupe_references(
                    [
                        evidence_record_to_reference(module.evidence[0], source_kind="module_graph", artifact_path="survey_summary.json")
                        for module in module_nodes
                        if module.relative_path == record.relative_path and module.evidence
                    ],
                    limit=2,
                ),
                confidence=ConfidenceBand.MEDIUM,
            )
            for record in survey_summary.high_velocity_files[:5]
        ]

        module_purpose_index = [
            CodebaseSectionEntry(
                title=profile.relative_path,
                summary=profile.purpose_statement,
                citations=dedupe_references(profile.evidence_references, limit=4),
                confidence=profile.purpose_confidence,
                is_inferred=True,
            )
            for profile in sorted(module_semantics.profiles, key=lambda item: item.relative_path)[:25]
        ]

        all_refs = dedupe_references(
            [
                *architecture_refs,
                *(reference for entry in critical_path_entries for reference in entry.citations),
                *(reference for entry in source_entries for reference in entry.citations),
                *(reference for entry in sink_entries for reference in entry.citations),
                *(reference for entry in known_debt_entries for reference in entry.citations),
                *(reference for entry in change_velocity_entries for reference in entry.citations),
                *(reference for entry in module_purpose_index[:10] for reference in entry.citations),
            ],
            limit=40,
        )

        return CodebaseContextDocument(
            metadata=metadata,
            analysis_root=str(repo_root),
            architecture_overview=architecture_overview,
            critical_path_entries=critical_path_entries,
            data_sources=source_entries,
            data_sinks=sink_entries,
            known_debt_entries=known_debt_entries,
            recent_change_velocity_entries=change_velocity_entries,
            module_purpose_index=module_purpose_index,
            evidence_references=all_refs,
            warning_codes=[],
            is_partial=not bool(source_entries and sink_entries and module_purpose_index),
        )

    def generate_CODEBASE_md(self, document: CodebaseContextDocument) -> str:
        """Render the required CODEBASE markdown sections."""

        lines = [
            "# CODEBASE",
            "",
            "## Architecture Overview",
            document.architecture_overview,
            "",
            self._render_evidence_block(document.evidence_references[:5]),
            "",
            "## Critical Path",
            self._render_section_entries(document.critical_path_entries),
            "",
            "## Data Sources & Sinks",
            "### Sources",
            self._render_section_entries(document.data_sources),
            "",
            "### Sinks",
            self._render_section_entries(document.data_sinks),
            "",
            "## Known Debt",
            self._render_section_entries(document.known_debt_entries),
            "",
            "## Recent Change Velocity",
            self._render_section_entries(document.recent_change_velocity_entries),
            "",
            "## Module Purpose Index",
            self._render_section_entries(document.module_purpose_index),
        ]
        return "\n".join(lines).strip() + "\n"

    def generate_onboarding_brief(
        self,
        *,
        metadata: SerializationMetadata,
        analysis_root: str,
        day_one_answers: DayOneAnswersPayload,
    ) -> OnboardingBrief:
        """Build the onboarding brief from the Day-One answers."""

        sections = []
        for answer in sorted(day_one_answers.answers, key=lambda item: item.question_id):
            observed = [
                f"Evidence from {reference.repository_path}{self._line_suffix(reference.line_start, reference.line_end)} via {reference.analysis_method.value}."
                for reference in answer.evidence_references
                if reference.observed_or_inferred == "observed"
            ]
            inferred = [answer.answer_text]
            if not observed:
                observed = ["Observed evidence is limited; see citations below."]
            sections.append(
                OnboardingQuestionSection(
                    question_id=answer.question_id,
                    question_text=answer.question_text,
                    observed_facts=observed,
                    inferred_conclusions=inferred,
                    citations=dedupe_references(answer.evidence_references, limit=6),
                    confidence=answer.confidence,
                    is_partial=answer.is_partial,
                )
            )
        return OnboardingBrief(
            metadata=metadata,
            analysis_root=analysis_root,
            sections=sections,
            warning_codes=day_one_answers.warnings,
            is_partial=any(section.is_partial for section in sections),
        )

    def render_onboarding_brief(self, brief: OnboardingBrief) -> str:
        """Render a concise onboarding brief with trust labels and citations."""

        lines = ["# Onboarding Brief", ""]
        for section in brief.sections:
            citation_lines = [f"- {format_evidence_reference(reference)}" for reference in section.citations]
            if not citation_lines:
                citation_lines = ["- No evidence available."]
            lines.extend(
                [
                    f"## {section.question_text}",
                    "Observed facts:",
                    *[f"- {fact}" for fact in section.observed_facts],
                    "Inferred conclusions:",
                    *[f"- {note}" for note in section.inferred_conclusions],
                    "Evidence citations:",
                    *citation_lines,
                    "",
                ]
            )
        return "\n".join(lines).strip() + "\n"

    def _build_provider(self) -> LLMProvider:
        if not self.settings.semantic_provider_enabled or not self.settings.openrouter_api_key:
            return NullProvider()
        return OpenRouterProvider(
            api_key=self.settings.openrouter_api_key,
            base_url=self.settings.openrouter_base_url,
            app_name=self.settings.openrouter_app_name,
            referer=self.settings.openrouter_referer,
        )

    def _dataset_entry(self, node: DatasetNode, summary: str) -> CodebaseSectionEntry:
        refs = dedupe_references(
            [
                evidence_record_to_reference(record, source_kind="lineage_graph", artifact_path="lineage_graph.json")
                for record in node.evidence[:2]
            ],
            limit=4,
        )
        return CodebaseSectionEntry(
            title=node.display_name or node.canonical_name,
            summary=summary,
            citations=refs,
            confidence=derive_confidence(refs),
        )

    def _module_entry(self, module: ModuleNode, profile, summary: str) -> CodebaseSectionEntry:
        refs = []
        for record in module.evidence[:1]:
            refs.append(evidence_record_to_reference(record, source_kind="module_graph", artifact_path="module_graph.json"))
        if profile is not None:
            refs.extend(profile.evidence_references[:2])
        refs = dedupe_references(refs, limit=4)
        profile_summary = f"{profile.purpose_statement} {summary}".strip() if profile is not None else summary
        return CodebaseSectionEntry(
            title=module.relative_path,
            summary=profile_summary,
            citations=refs,
            confidence=derive_confidence(refs),
            is_inferred=profile is not None,
        )

    def _find_lineage_boundary_nodes(self, lineage_graph: GraphPayload, boundary: str) -> list[DatasetNode]:
        incoming: dict[str, int] = {node.node_id or "": 0 for node in lineage_graph.nodes}
        outgoing: dict[str, int] = {node.node_id or "": 0 for node in lineage_graph.nodes}
        for edge in lineage_graph.edges:
            outgoing[edge.source_node_id] = outgoing.get(edge.source_node_id, 0) + 1
            incoming[edge.target_node_id] = incoming.get(edge.target_node_id, 0) + 1
        dataset_nodes = [node for node in lineage_graph.nodes if isinstance(node, DatasetNode)]
        if boundary == "sources":
            return [
                node
                for node in sorted(dataset_nodes, key=lambda item: item.canonical_name)
                if incoming.get(node.node_id or "", 0) == 0 and outgoing.get(node.node_id or "", 0) > 0
            ]
        return [
            node
            for node in sorted(dataset_nodes, key=lambda item: item.canonical_name)
            if outgoing.get(node.node_id or "", 0) == 0 and incoming.get(node.node_id or "", 0) > 0
        ]

    def _render_section_entries(self, entries: list[CodebaseSectionEntry]) -> str:
        if not entries:
            return "- No evidence available."
        lines: list[str] = []
        for entry in entries:
            trust = "Inferred" if entry.is_inferred else "Observed"
            lines.append(f"- **{entry.title}**: {entry.summary}")
            lines.append(f"  Trust: {trust}; confidence: {entry.confidence.value}.")
            if entry.citations:
                lines.append("  Evidence:")
                lines.extend(f"  - {format_evidence_reference(reference)}" for reference in entry.citations)
        return "\n".join(lines)

    def _render_evidence_block(self, references: list[EvidenceReference]) -> str:
        if not references:
            return "Evidence: no direct citations available."
        lines = ["Evidence:"]
        lines.extend(f"- {format_evidence_reference(reference)}" for reference in references)
        return "\n".join(lines)

    @staticmethod
    def _line_suffix(line_start: int | None, line_end: int | None) -> str:
        if line_start is None:
            return ""
        if line_end is None or line_end == line_start:
            return f":L{line_start}"
        return f":L{line_start}-L{line_end}"
